name: Standard Docker Container Versioning

on:
  workflow_call:
    outputs:
      tags:
        description: "tags of the docker image"
        value: ${{ jobs.set_env.outputs.tags }}
        
jobs:
  set_env:
    name: Create version tag
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.version_step.outputs.tags }}
    steps:
    - id: version_step
      run:  |
        if [ "${{ github.event_name }}" = "release" ]; then
          echo "tags=latest,${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
        fi
